sonar.host.url=http://localhost:9000
sonar.projectKey=gestor-cursos-react
sonar.projectName=Gestor Cursos React
sonar.projectVersion=1.0
sonar.sources=src
sonar.exclusions=node_modules/**,dist/**
sonar.sourceEncoding=UTF-8
sonar.token=sqp_d1d12dad979de32a9ba05bcffe0e7f1ea59a5dae
